### PR TITLE
Fix #4, #5, #6, #7: Implement event stream APIs for transactions

### LINKED ISSUE #4: API: Transaction history -to event stream-
(almost same with #3)

This api can be used to check how the transmitted transaction(from client) is finished,
* tx gets consensus successfully?
* or tx is failed because of some reason
---
* If tx gets consensus successfully, the response will have `BlockTransaction` data.
* If failed, the response will have `BlockTransactionHistory` data.

### PR DESCRIPTION
**Pull request by kfangw**
### Github Issue
#4 ~ #7

### CODE REVIEW

File: lib/api.go [hunk 1]
```diff
@@ -30,37 +34,37 @@ func streaming(o *observable.Observable, w http.ResponseWriter, event string, ca
 		return
 	}
 
-	closeChan := make(chan bool)
+	consumerChan := make(chan struct{})
```
Comment (kfangw) [inline lib/api.go]: There was a problem when several goroutine runs concurrently.
If a event occur during `o.Off(event, observerFunc)` is being called,
the callback function trying to send message to `messageChan`.
However messageChan receiver already disappear.

Because of this reason, the consumerChan is introduced to notify the messageChan receiver is gone.

File: lib/api_account.go [hunk 2]
```diff
@@ -26,31 +28,169 @@ func GetAccountHandler(s *sebakstorage.LevelDBBackend) http.HandlerFunc {
...
-		if s, err = ba.Serialize(); err != nil {
-			http.Error(w, "Error reading request body", http.StatusInternalServerError)
-			return
-		}
 
 		switch r.Header.Get("Accept") {
 		case "text/event-stream":
-			event := fmt.Sprintf("saved-%s", address)
+
+			var readyChan = make(chan struct{})
```
Comment (kfangw) [inline lib/api_account.go]: To handle previous data which already stored in the block,
Getting the information trigger "iterate" event

File: lib/block_transaction.go [hunk 3]
```diff
@@ -50,7 +51,7 @@ type BlockTransaction struct {
 func NewBlockTransactionFromTransaction(tx Transaction, message []byte) BlockTransaction {
 	var opHashes []string
 	for _, op := range tx.B.Operations {
-		opHashes = append(opHashes, op.MakeHashString())
+		opHashes = append(opHashes, NewBlockOperationKey(op, tx))
```
Comment (kfangw) [inline lib/block_transaction.go]: It was a bug.

**Comment by kfangw** [comment]
sorry about the broken CI. i will fix it.

File: lib/api_metric.go [hunk 4]
```diff
@@ -0,0 +1 @@
+package sebak
```
Comment (Geod24) [inline lib/api_metric.go]: Unused ?

File: lib/api_node.go [hunk 5]
```diff
@@ -0,0 +1 @@
+package sebak
```
Comment (Geod24) [inline lib/api_node.go]: Unused ?

**Comment by Geod24** [comment]
I renamed the issue to be clearer. Could you amend the commit message accordingly, and provide a rationale ? That would help reviewers and future history-digger big time.

File: lib/api_account.go [hunk 6]
```diff
@@ -26,31 +28,172 @@ func GetAccountHandler(s *sebakstorage.LevelDBBackend) http.HandlerFunc {
...
+		var err error
+		var s []byte
+
+		switch r.Header.Get("Accept") {
+		case "text/event-stream":
+			var readyChan = make(chan struct{})
+			iterateId := sebakcommon.GetUniqueIDFromUUID()
+			go func() {
+				<-readyChan
+				iterFunc, closeFunc := GetBlockTransactionsByAccount(storage, address, false)
```
Comment (spikeekips) [inline lib/api_account.go]: To get the latest `BlockTransaction` of account, the last argument must be `false`, right?

File: lib/api.go [hunk 7]
```diff
@@ -12,12 +12,16 @@ import (
 
 func AddAPIHandlers(s *sebakstorage.LevelDBBackend) func(ctx context.Context, t *sebaknetwork.HTTP2Network) {
 	fn := func(ctx context.Context, t *sebaknetwork.HTTP2Network) {
-		t.AddAPIHandler("/account/{address}", GetAccountHandler(s)).Methods("GET")
+		t.AddAPIHandler(GetAccountHandlerPattern, GetAccountHandler(s)).Methods("GET")
+		t.AddAPIHandler(GetAccountTransactionsHandlerPattern, GetAccountTransactionsHandler(s)).Methods("GET")
+		t.AddAPIHandler(GetAccountOperationsHandlerPattern, GetAccountOperationsHandler(s)).Methods("GET")
+		t.AddAPIHandler(GetTransactionByHashHandlerPattern, GetTransactionByHashHandler(s)).Methods("GET")
```
Comment (kfangw) [inline lib/api.go]: I want to put the pattern and its handler together.
That is the reason why I use constant here.
Btw, we are planing to refactor APIs and handlers, at that time the point you are considering may be solved.

File: lib/api.go [hunk 8]
```diff
@@ -30,37 +34,37 @@ func streaming(o *observable.Observable, w http.ResponseWriter, event string, ca
...
-			closeChan <- true
+			//TODO: handle the error
 			return
 		}
-		messageChan <- s
+
+		select {
+		case messageChan <- s:
+		case <-consumerChan:
+		}
```
[the remark this answers is not in the document]
Comment (kfangw) [reply lib/api.go]: The select statement is used for waiting events.
this statement wait until one of two cases triggered.

This callback function(`observerFunc`) is called in parallel, and while the function  being executed receiver of the messageChan may dismissed(http handler function returned). At the specific time, this callback function is blocked.

To solve this problem, I intoroduced the `consumerChan` to notify to the callback function that the receiver is no longer exist.

File: lib/api_account.go (hunk 6 above)
Comment (kfangw) [reply lib/api_account.go]: to get latest element, the last argument should be `true`.
It is not easy to explain in text. I will explain about this in person. ^^

File: lib/api_metric.go (hunk 4 above)
Comment (kfangw) [reply lib/api_metric.go]: Another PR will add code for this file.

Comment (Geod24) [reply lib/api_metric.go]: Then let's not add this empty file here, but in another PR

**Comment by Geod24** [comment]
```console
$ docker build . -t sebak && docker rmi -f $(docker images -f "dangling=true" -q)
[...]
$ docker run --net host --rm -it --env-file=docker/node3.env sebak
successfully created genesis block
INFO[06-27|04:11:37] Starting Sebak                           module=main
DBUG[06-27|04:11:37] parsed flags:                            module=main
	network-id=sebak-test-network
	endpoint=https://localhost:2823
	storage=file:///sebak/db
	tls-cert=sebak.crt
	tls-key=sebak.key
	log-level=debug
	log-output=<stdout>
	sign-threshold=60
	accept-threshold=60
	validator#0="alias=node1 address=GDIRF4UWPACXPPI4GW7CMTACTCNDIKJEHZK44RITZB4TD3YUM6CCVNGJ endpoint=https://localhost:2821"
	validator#1="alias=node2 address=GAYGELM74WJMKSLDN5YP2VAMP64WC4IXIGICUNK2SCVIT7KPTLY7M3MW endpoint=https://localhost:2822"
panic: interface conversion: interface {} is func(*sebakstorage.LevelDBBackend) func(context.Context, *sebaknetwork.HTTP2Network), not func(context.Context, *sebaknetwork.HTTP2Network)

goroutine 1 [running]:
boscoin.io/sebak/lib/network.(*HTTP2Network).AddHandler(0xc4200ceb00, 0x9e11a0, 0xc4201a62a0, 0xc420095680, 0x1, 0x1, 0x9e32a0, 0x9e11a0)
	/go/src/boscoin.io/sebak/lib/network/http2_network.go:160 +0x91
boscoin.io/sebak/lib.(*NodeRunner).Ready(0xc42009a820)
	/go/src/boscoin.io/sebak/lib/node_runner.go:69 +0xce
boscoin.io/sebak/lib.(*NodeRunner).Start(0xc42009a820, 0x12, 0x9e4d00)
	/go/src/boscoin.io/sebak/lib/node_runner.go:74 +0x2f
boscoin.io/sebak/cmd/sebak/cmd.runNode()
	/go/src/boscoin.io/sebak/cmd/sebak/cmd/node.go:284 +0x774
boscoin.io/sebak/cmd/sebak/cmd.init.2.func1(0xc4200e7b80, 0xc4200b2300, 0x0, 0x6)
	/go/src/boscoin.io/sebak/cmd/sebak/cmd/node.go:115 +0x25
boscoin.io/sebak/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200e7b80, 0xc4200b2240, 0x6, 0x6, 0xc4200e7b80, 0xc4200b2240)
	/go/src/boscoin.io/sebak/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
boscoin.io/sebak/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc85b20, 0xc85d80, 0xc420063f78, 0x405dac)
	/go/src/boscoin.io/sebak/vendor/github.com/spf13/cobra/command.go:852 +0x30a
boscoin.io/sebak/vendor/github.com/spf13/cobra.(*Command).Execute(0xc85b20, 0x2, 0x0)
	/go/src/boscoin.io/sebak/vendor/github.com/spf13/cobra/command.go:800 +0x2b
boscoin.io/sebak/cmd/sebak/cmd.Execute()
	/go/src/boscoin.io/sebak/cmd/sebak/cmd/init.go:22 +0x2d
main.main()
	/go/src/boscoin.io/sebak/cmd/sebak/main.go:8 +0x20
```

I was using e6c5fbe9b7e6a7c050b571d5d8e7bf15dd4289a5

**Comment by kfangw** [comment]
@Geod24 fixed the bug

**Comment by Geod24** [comment]
Could you provide some of the `curl` command (or something else) you used for testing ?
So far I've been trying the following:
```console
$ curl -k https://127.0.0.1:2822/account/GDIRF4UWPACXPPI4GW7CMTACTCNDIKJEHZK44RITZB4TD3YUM6CCVNGJ
404 page not found
```

The address used is the genesis account, using the docker setup.

**Comment by spikeekips** [comment]
@kfangw There are some bugs in https://github.com/kfangw/sebak/blob/4b9a838329fd1a00ba7c4152267ba4fcd49c549e/lib/network/http2_network.go#L165 . If you can, please fix it. `RouterNameNode` must be `RouterNameAPI`. After this is fixed, we can run 'curl' like this,

```
$ curl --insecure -v https://localhost:12345/api/account/GB6YNDSNKT3BOVYJTEZRKHWNDQRBQ26DPRF6J6CUCFED4MD37JIHV7MY
```

**Comment by kfangw** [comment]
@spikeekips I just found the bug -_-
@Geod24 Sorry for the annoying. I've tested only the handlers thats why the bugs still here.
btw, you can test it now. it works.

**Comment by kfangw** [comment]
If everything ok then I will merge this PR into this branch
https://github.com/kfangw/sebak/pull/2

**Comment by Geod24** [comment]
Hold on I'm still testing. But so far it's promising.

**Comment by kfangw** [comment]
Sure. Let me know if there is an issue or you finished your test.
During you working, I am going to write client code for these APIs.

File: lib/api_test.go [hunk 9]
```diff
@@ -3,92 +3,409 @@ package sebak
...
 	defer storage.Close()
 
 	router := mux.NewRouter()
-	router.HandleFunc("/account/{address}", GetAccountHandler(storage)).Methods("GET")
-	server := &http.Server{Addr: ":5000", Handler: router}
-	go server.ListenAndServe()
+	router.HandleFunc(GetAccountHandlerPattern, GetAccountHandler(storage)).Methods("GET")
+
+	ts := httptest.NewServer(router)
+	defer ts.Close()
```
Comment (spikeekips) [inline lib/api_test.go]: We need to check the connection availability. Sometimes, testing was failed because server was not ready. How about adding this kind of routine after `httptest.NewServer`?
```
// check connection availability
for {
	if _, err := net.DialTimeout("tcp", <localhost:XXX>, 100*time.Millisecond); err != nil {
		time.Sleep(50 * time.Millisecond)
		continue
	}
	break
}
```

Comment (spikeekips) [inline lib/api_test.go]: In some circumstances, especially CircleCI or Travis, closing http server was hanged. We need stronger way to close server like `Shutdown`,
```
defer func() {
	timer := time.NewTimer(500 * time.Millisecond)
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		ts.Shutdown(ctx)
	}()
	<-timer.C
	cancel()
}()
```

Comment (spikeekips) [reply lib/api_test.go]: @kfangw I am confused, the normal `http.Server` needs my previous comment, but `httptest.Server` does not need this checking :)

Comment (spikeekips) [reply lib/api_test.go]: @kfangw Please see https://github.com/bosnet/sebak/pull/121#discussion_r198686738 .

Comment (kfangw) [reply lib/api_test.go]: I was confused why you asking this changed..

**Comment by kfangw** [comment]
@spikeekips @Geod24 @anarcher @cmcm2222 
While reviewing, i will do integration test manually which may not caught by unit testing.
If there is no problem in this PR, I will merge it.
Please leave your comment guys.

**Comment by Geod24** [comment]
> It's a lot of code, and it would be more than welcome to add documentation to all those new methods.

Ping on this

**Comment by kfangw** [comment]
@Geod24
`streaming` function is the most important for this change.
Hence, I attached some documentation above the function.

I searched standard comment format for godoc. but there is no standard format like C++ function comment style.

**Comment by kfangw** [comment]
@Geod24 may I merge it?
