### PR TITLE
Fix #85 `sebak generate` triggers `value out of range` error

### LINKED ISSUE #85: `sebak generate` triggers `value out of range` error
```
$ sebak genesis SBXBRFM4UDBHREM2XRM6IIOXNR52N6NAKWIMR7MR4XMNJ5VA4WC27QDY
error: invalid '--balance'; strconv.ParseInt: parsing "10000000000000000000": value out of range
```

`sebak genesis` with the default balance, `1,000,000,000,000.0000000` occurs error, it is caused by `sebak.AmountFromString`. `strconv.ParseInt` should be changed to use `ParseUint`.

### PR DESCRIPTION
**Pull request by zzim2x**
initial balance is out of range of a 64 bit integer value.

### CODE REVIEW

**Comment by Geod24** [comment]
Needs a rebase (sorry), since I deleted some of the code.

File: lib/data.go [hunk 1]
```diff
@@ -97,7 +97,7 @@ func (a Amount) MustSub(sub Amount) Amount {
 
 // Implement JSON's Marshaler interface
 func (a Amount) MarshalJSON() ([]byte, error) {
-	return []byte(fmt.Sprintf("\"%s\"", a.String())), nil
+	return []byte(fmt.Sprintf("\"%s\"", strconv.FormatUint(uint64(a), 10))), nil
```
Comment (Geod24) [inline lib/data.go]: I think that should be reverted ;)

Comment (zzim2x) [reply lib/data.go]: I got it.
