### PR TITLE
Fix #138: Wait until server is ready to start tests

### LINKED ISSUE #138: 'TestHTTP2NetworkXX' failed; it was caused by empty response
```
--- FAIL: TestHTTP2NetworkSendMessage (0.12s)
	http2_network_test.go:206: 
			Error Trace:	http2_network_test.go:206
			Error:      	Not equal: 
			            	expected: ""
			            	actual  : "{\"T\":\"dummy-message\",\"Hash\":\"5sD1FhUsNwHzFnHQVQa6fm7H8Rhuz8M7CXtSondscTVc\",\"Data\":\"findme\"}"
			            	
			            	Diff:
			            	--- Expected
			            	+++ Actual
			            	@@ -1 +1 @@
			            	-
			            	+{"T":"dummy-message","Hash":"5sD1FhUsNwHzFnHQVQa6fm7H8Rhuz8M7CXtSondscTVc","Data":"findme"}
			Test:       	TestHTTP2NetworkSendMessage
			Messages:   	The sendMessage and the return should be the same.
127.0.0.1 - - [27/Jun/2018:09:42:23 +0000] "POST /node/ballot HTTP/2.0" 200 91 "" "v-n1"
FAIL
FAIL	github.com/spikeekips/sebak/lib/network	34.382s
```

### PR DESCRIPTION
**Pull request by kfangw**
### Github Issue
#138 

usually, /ping api used for checking health of a server.

I use nodeinfo insead of /ping

### CODE REVIEW

File: lib/network/http2_network_test.go [hunk 1]
```diff
@@ -67,6 +67,21 @@ const (
 	keyPath  = "key.pem"
 )
 
+func pingAndWait(t *testing.T, c0 NetworkClient) {
```
Comment (Geod24) [inline lib/network/http2_network_test.go]: Comment ? :)
