### PR TITLE
FIX #150 transaction checkpoint validation

### LINKED ISSUE #150: Consensus fail for payment transaction
I am trying send coin via wallet.
bellow is my step

prepare docker image and containers
```
docker build . -t sebak && docker rmi -f $(docker images -f "dangling=true" -q)

docker run --net=host --rm -it --env-file=docker/node1.env sebak
docker run --net=host --rm -it --env-file=docker/node2.env sebak
docker run --net=host --rm -it --env-file=docker/node3.env sebak
```

generate 3 key pairs
```
[~/goworkspace/src/boscoin.io/sebak] sebak key generate
       Secret Seed: SBRJ7NFNW6Q7CKGLILMEWHAZX353EKV2HXOWMHS7UGTBOQGH2OM5J6DS
    Public Address: GCXQHQDSU6DHNW3YV2QXGEFERQ3E4WIHMVUIWBRGAGT7765WOPUHW54Y
[~/goworkspace/src/boscoin.io/sebak] sebak key generate
       Secret Seed: SDKZB4CROCE4OJIFS4ZX6BIBD7TKS7BEGTFLYBKS2CV24JSJA3WJKBSM
    Public Address: GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4
[~/goworkspace/src/boscoin.io/sebak] sebak key generate
       Secret Seed: SBO3SK4AXR7ANLAOKNAVJLE23I2MT6ZTJTOWZGS7AJ6WFMCL764HVPXC
    Public Address: GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED
```

send 10000000 to 3 account
```
docker build . -t sebak && docker run --rm --network host -it sebak wallet payment GCXQHQDSU6DHNW3YV2QXGEFERQ3E4WIHMVUIWBRGAGT7765WOPUHW54Y 10000000 SBECGI3FSCYHNQIMANNCWQSVA6S5C6L4BXFKAPMBAMI5V47NWXNE37MN --endpoint=https://127.0.0.1:2822 --create ;docker build . -t sebak && docker run --rm --network host -it sebak wallet payment GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4 10000000 SBECGI3FSCYHNQIMANNCWQSVA6S5C6L4BXFKAPMBAMI5V47NWXNE37MN --endpoint=https://127.0.0.1:2822 --create ;docker build . -t sebak && docker run --rm --network host -it sebak wallet payment GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED 10000000 SBECGI3FSCYHNQIMANNCWQSVA6S5C6L4BXFKAPMBAMI5V47NWXNE37MN --endpoint=https://127.0.0.1:2822 --create
```

prepare another docker container to curl
```
docker run --net host --rm -it ubuntu:14.04 bash
apt-get update
apt-get install curl
```

in the docker container call the account api
```
echo "====1====" ;curl -k https://127.0.0.1:2823/api/account/GCXQHQDSU6DHNW3YV2QXGEFERQ3E4WIHMVUIWBRGAGT7765WOPUHW54Y ;echo ;echo "====2====";curl -k https://127.0.0.1:2823/api/account/GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4 ;echo ;echo "====3====" ;curl -k https://127.0.0.1:2823/api/account/GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED ; echo
```
==>
```
====1====
{"Address":"GCXQHQDSU6DHNW3YV2QXGEFERQ3E4WIHMVUIWBRGAGT7765WOPUHW54Y","Balance":"10000000","Checkpoint":"5nc4PvPKMxDTM6ets3hudktkA-5nc4PvPKMxDTM6ets3hudktkA"}
====2====
{"Address":"GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4","Balance":"10000000","Checkpoint":"9oJ7Y2xU6oCPhEQkrC9uikeLai38B5uFU3ZLyBc5hhLm-9oJ7Y2xU6oCPhEQkrC9uikeLai38B5uFU3ZLyBc5hhLm"}
====3====
{"Address":"GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED","Balance":"10000000","Checkpoint":"Aq6yzC8VraFAQnQ3DuBEFwDHZQCoZmnQtRKokJ9LMcjU-Aq6yzC8VraFAQnQ3DuBEFwDHZQCoZmnQtRKokJ9LMcjU"}
```

each account have balance 1000

now I tried send from 1->3
```
docker build . -t sebak && docker run --rm --network host -it sebak wallet payment GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED 130000 SBRJ7NFNW6Q7CKGLILMEWHAZX353EKV2HXOWMHS7UGTBOQGH2OM5J6DS --endpoint=https://127.0.0.1:2822
```
2->3
```
docker build . -t sebak && docker run --rm --network host -it sebak wallet payment GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED 120000 SDKZB4CROCE4OJIFS4ZX6BIBD7TKS7BEGTFLYBKS2CV24JSJA3WJKBSM --endpoint=https://127.0.0.1:2822
```

3->2
```
docker build . -t sebak && docker run --rm --network host -it sebak wallet payment GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4 120000 SBO3SK4AXR7ANLAOKNAVJLE23I2MT6ZTJTOWZGS7AJ6WFMCL764HVPXC --endpoint=https://127.0.0.1:2822
```

Check the balance again
```
docker build . -t sebak && docker run --rm --network host -it sebak wallet payment GCXQHQDSU6DHNW3YV2QXGEFERQ3E4WIHMVUIWBRGAGT7765WOPUHW54Y 10000000 SBECGI3FSCYHNQIMANNCWQSVA6S5C6L4BXFKAPMBAMI5V47NWXNE37MN --endpoint=https://127.0.0.1:2822 --create ;docker build . -t sebak && docker run --rm --network host -it sebak wallet payment GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4 10000000 SBECGI3FSCYHNQIMANNCWQSVA6S5C6L4BXFKAPMBAMI5V47NWXNE37MN --endpoint=https://127.0.0.1:2822 --create ;docker build . -t sebak && docker run --rm --network host -it sebak wallet payment GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED 10000000 SBECGI3FSCYHNQIMANNCWQSVA6S5C6L4BXFKAPMBAMI5V47NWXNE37MN --endpoint=https://127.0.0.1:2822 --create
```
==>
```
====1====
{"Address":"GCXQHQDSU6DHNW3YV2QXGEFERQ3E4WIHMVUIWBRGAGT7765WOPUHW54Y","Balance":"9860000","Checkpoint":"F3RoU6TkGe1Wrn8bd4fzZNtoBkZAQqbF8gpk6218CmKW-F3RoU6TkGe1Wrn8bd4fzZNtoBkZAQqbF8gpk6218CmKW"}
====2====
{"Address":"GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4","Balance":"10000000","Checkpoint":"9oJ7Y2xU6oCPhEQkrC9uikeLai38B5uFU3ZLyBc5hhLm-9oJ7Y2xU6oCPhEQkrC9uikeLai38B5uFU3ZLyBc5hhLm"}
====3====
{"Address":"GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED","Balance":"10130000","Checkpoint":"5nc4PvPKMxDTM6ets3hudktkA-F3RoU6TkGe1Wrn8bd4fzZNtoBkZAQqbF8gpk6218CmKW"}
```

`it seems like that Only first account can get/send coins to another account`

Bellows is log message when 2->3 failed
```
DBUG[06-29|06:08:49] got message from client`                 module=sebak node=GAYG.TLY7 message="{\"Type\":\"message\",\"Data\":\"eyJUIjoidHJhbnNhY3Rpb24i"
DBUG[06-29|06:08:49] message is transaction                   module=sebak node=GAYG.TLY7
DBUG[06-29|06:08:49] saved in history                         module=sebak node=GAYG.TLY7 transaction=G583PEDTJQc5Ez4rrYkfWmNk3WLwvQp24P23J8iRaP8h
DBUG[06-29|06:08:49] ballot from client will be broadcasted   module=sebak node=GAYG.TLY7 ballot=G583PEDTJQc5Ez4rrYkfWmNk3WLwvQp24P23J8iRaP8h
127.0.0.1 - - [29/Jun/2018:06:08:49 +0000] "POST /node/ballot HTTP/2.0" 200 1006 "" "v-GDTE.6RAE"
DBUG[06-29|06:08:49] got ballot                               module=sebak node=GAYG.TLY7 message="{\"Type\":\"ballot\",\"Data\":\"eyJUIjoiYmFsbG90IiwiSCI6e"
127.0.0.1 - - [29/Jun/2018:06:08:49 +0000] "POST /node/ballot HTTP/2.0" 200 1006 "" "v-GDIR.M6CC"
DBUG[06-29|06:08:49] got ballot                               module=sebak node=GAYG.TLY7 message="{\"Type\":\"ballot\",\"Data\":\"eyJUIjoiYmFsbG90IiwiSCI6e"
DBUG[06-29|06:08:49] check threshold                          module=sebak state=INIT threshold=3 yes=3 no=0 policy="{\"accept\":60,\"init\":100,\"sign\":60,\"validators\":3}"
DBUG[06-29|06:08:49] ballot will be broadcasted               module=sebak node=GAYG.TLY7 ballot=G583PEDTJQc5Ez4rrYkfWmNk3WLwvQp24P23J8iRaP8h isNew=false
127.0.0.1 - - [29/Jun/2018:06:08:49 +0000] "POST /node/ballot HTTP/2.0" 200 1005 "" "v-GDTE.6RAE"
DBUG[06-29|06:08:49] got ballot                               module=sebak node=GAYG.TLY7 message="{\"Type\":\"ballot\",\"Data\":\"eyJUIjoiYmFsbG90IiwiSCI6e"
DBUG[06-29|06:08:49] check threshold                          module=sebak state=SIGN threshold=2 yes=0 no=2 policy="{\"accept\":60,\"init\":100,\"sign\":60,\"validators\":3}"
DBUG[06-29|06:08:49] consensus of this ballot will be closed  module=sebak ballot=G583PEDTJQc5Ez4rrYkfWmNk3WLwvQp24P23J8iRaP8h
DBUG[06-29|06:08:49] consensus closed                         module=sebak node=GAYG.TLY7
127.0.0.1 - - [29/Jun/2018:06:08:49 +0000] "POST /node/ballot HTTP/2.0" 200 1005 "" "v-GDIR.M6CC"
DBUG[06-29|06:08:49] got ballot                               module=sebak node=GAYG.TLY7 message="{\"Type\":\"ballot\",\"Data\":\"eyJUIjoiYmFsbG90IiwiSCI6e"
WARN[06-29|06:08:49] failed to add VotingResult               module=sebak MessageHash=G583PEDTJQc5Ez4rrYkfWmNk3WLwvQp24P23J8iRaP8h error="{\"code\":121,\"message\":\"ballot has invalid state\"}"
EROR[06-29|06:08:49] failed to handle ballot                  module=sebak node=GAYG.TLY7 error="{\"code\":114,\"message\":\"`VotingResult` not found\"}"
127.0.0.1 - - [29/Jun/2018:06:08:50 +0000] "POST /node/connect HTTP/2.0" 200 265 "" "v-GDTE.6RAE"
```

### PR DESCRIPTION
**Pull request by kfangw**
### Requirements
Tx is Transaction
Ax is Account
AxC is Checkpoint of the Account

assume that Tx0 is exist
```
====1====
{"Address":"GCXQHQDSU6DHNW3YV2QXGEFERQ3E4WIHMVUIWBRGAGT7765WOPUHW54Y","Balance":"10000000","Checkpoint":"5nc4PvPKMxDTM6ets3hudktkA-9oJ7Y2xU6oCPhEQkrC9uikeLai38B5uFU3ZLyBc5hhLm"}
====2====
{"Address":"GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED","Balance":"10000000","Checkpoint":"Aq6yzC8VraFAQnQ3DuBEFwDHZQCoZmnQtRKokJ9LMcjU-BYw5mwFdu1xdqHnBSyVWY5Dh9rxdiNTYhzYgL615cmby"}
====3====
{"Address":"GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4","Balance":"10000000","Checkpoint":"9oJ7Y2xU6oCPhEQkrC9uikeLai38B5uFU3ZLyBc5hhLm-Aq6yzC8VraFAQnQ3DuBEFwDHZQCoZmnQtRKokJ9LMcjU"}
```

T1: A1 --> A2
A1C: T0-T0
A2C: T0-T1
```
====1====
{"Address":"GCXQHQDSU6DHNW3YV2QXGEFERQ3E4WIHMVUIWBRGAGT7765WOPUHW54Y","Balance":"9860000","Checkpoint":"8vVwuTm2bmCkQxQpA9ABZEH2bwgX2tE3S3m43s3fDu2a-8vVwuTm2bmCkQxQpA9ABZEH2bwgX2tE3S3m43s3fDu2a"}
====2====
{"Address":"GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED","Balance":"10130000","Checkpoint":"5nc4PvPKMxDTM6ets3hudktkA-8vVwuTm2bmCkQxQpA9ABZEH2bwgX2tE3S3m43s3fDu2a"}
====3====
{"Address":"GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4","Balance":"10000000","Checkpoint":"9oJ7Y2xU6oCPhEQkrC9uikeLai38B5uFU3ZLyBc5hhLm-Aq6yzC8VraFAQnQ3DuBEFwDHZQCoZmnQtRKokJ9LMcjU"}
```

T2: A2 --> A3
A2C: T2-T2
A3C: T0-T2
```
====1====
{"Address":"GCXQHQDSU6DHNW3YV2QXGEFERQ3E4WIHMVUIWBRGAGT7765WOPUHW54Y","Balance":"9860000","Checkpoint":"8vVwuTm2bmCkQxQpA9ABZEH2bwgX2tE3S3m43s3fDu2a-8vVwuTm2bmCkQxQpA9ABZEH2bwgX2tE3S3m43s3fDu2a"}
====2====
{"Address":"GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED","Balance":"10000000","Checkpoint":"JBYNTUUqv8GGuSM5mqhJyM47KEibhCMN31FJxFFgjJ4p-JBYNTUUqv8GGuSM5mqhJyM47KEibhCMN31FJxFFgjJ4p"}
====3====
{"Address":"GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4","Balance":"10120000","Checkpoint":"5nc4PvPKMxDTM6ets3hudktkA-JBYNTUUqv8GGuSM5mqhJyM47KEibhCMN31FJxFFgjJ4p"}
```

T3: A2 --> A3 (again)
A2C: T3-T3
A3C: T2-T3
```
====1====
{"Address":"GCXQHQDSU6DHNW3YV2QXGEFERQ3E4WIHMVUIWBRGAGT7765WOPUHW54Y","Balance":"9860000","Checkpoint":"8vVwuTm2bmCkQxQpA9ABZEH2bwgX2tE3S3m43s3fDu2a-8vVwuTm2bmCkQxQpA9ABZEH2bwgX2tE3S3m43s3fDu2a"}
====2====
{"Address":"GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED","Balance":"9870000","Checkpoint":"84kC8vuV19o4Kqzaw1o9zQERLQvdZsSxLAKRgV6of7Yu-84kC8vuV19o4Kqzaw1o9zQERLQvdZsSxLAKRgV6of7Yu"}
====3====
{"Address":"GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4","Balance":"10240000","Checkpoint":"JBYNTUUqv8GGuSM5mqhJyM47KEibhCMN31FJxFFgjJ4p-84kC8vuV19o4Kqzaw1o9zQERLQvdZsSxLAKRgV6of7Yu"}
```

To make Transaction T3, wallet get the A2's checkpoint(T2-T2).
With the checkpoint wallet submit T3.

ISAAC validate the checkpoint
Transaction for the checkpoint(T2-T2) is T2
Source Address of the transaction is A2.
Hence, just check like this
```
if tx.B.Source != bt.Source
```

T4: A3 --> A1
A3C: T4-T4
A1C: T2-T4
```
====1====
{"Address":"GCXQHQDSU6DHNW3YV2QXGEFERQ3E4WIHMVUIWBRGAGT7765WOPUHW54Y","Balance":"9980000","Checkpoint":"JBYNTUUqv8GGuSM5mqhJyM47KEibhCMN31FJxFFgjJ4p-6GNMLQhPFEsvix3PBySF7KjfVAvQbJWaETpcvqDbCqGH"}
====2====
{"Address":"GA2GII5TSFTVDHS23HBVYEHOLFNGATUPRNDJMVD2FWA4ZOI3B2TSAHED","Balance":"9870000","Checkpoint":"84kC8vuV19o4Kqzaw1o9zQERLQvdZsSxLAKRgV6of7Yu-84kC8vuV19o4Kqzaw1o9zQERLQvdZsSxLAKRgV6of7Yu"}
====3====
{"Address":"GB6UZVTLJF545XA4ZXDGH2AI7RD62YVIRL7H5MCPHTXZ4BOHOPUSLCM4","Balance":"10110000","Checkpoint":"6GNMLQhPFEsvix3PBySF7KjfVAvQbJWaETpcvqDbCqGH-6GNMLQhPFEsvix3PBySF7KjfVAvQbJWaETpcvqDbCqGH"}
```

To make Transaction T4, wallet get the A3's checkpoint(T2-T3).
With the checkpoint wallet submit T4.

ISAAC validate the checkpoint
Transaction for the checkpoint(T2-T3) is T3
Source Address of the transaction is A2 (which is not A3)
Hence, need to extract target addresses of the transaction when save the transaction
```
for _, op := range bt.transaction.B.Operations {
	target := op.B.TargetAddress()
	bt.Targets = append(bt.Targets, target)
}
```
now, ISAAC validate source address of the T4 is in the target addresses of transaction T3
```
if _, found := sebakcommon.InStringArray(bt.Targets, tx.B.Source); !found {
	return
}
```

### Github Issue
#150

### CODE REVIEW

**Comment by spikeekips** [comment]
@kfangw I wish this PR will fill the missing hole of testnet. :+1 허리허리 머지머지. ㅎㅎ

**Comment by Charleslee522** [comment]
I want to talk about it more. I don’t know why, but I feel something weird.
I’m going to think deeply and comment tomorrow morning :)

**Comment by spikeekips** [comment]
@Charleslee522 As we know, the current checkpoint mechanism was already banned by our members, but please ask me, I will help your understanding on this kind of weired checkpoint concept.

**Comment by kfangw** [comment]
@Charleslee522 It is bug fix. Hence I will merge this branch. 
We can talk about transaction verification scheme in depth later.

File: lib/node_runner_checker.go [hunk 1]
```diff
@@ -275,9 +275,21 @@ func CheckNodeRunnerHandleBallotVotingHole(c sebakcommon.Checker, args ...interf
...
 			return
 		}
+
+		// The transaction was invoked by the account
+		if checkPoint[0] == checkPoint[1] {
+			if tx.B.Source != bt.Source {
+				return
+			}
+		} else { //The transaction was invoked by another account
+			if _, found := sebakcommon.InStringArray(bt.Targets, tx.B.Source); !found {
```
Comment (Charleslee522) [inline lib/node_runner_checker.go]: Just curious, why is checking the target address needed?
If the purpose of this pr is to fix bug, then only the code of this part is enough.
```
		if checkPoint[0] == checkPoint[1] {
			if tx.B.Source != bt.Source {
				return
			}
		}
```
I already checked #150 scenario(thanks @kfangw) with commented this part like,
```
} else { //The transaction was invoked by another account
			// if _, found := sebakcommon.InStringArray(bt.Targets, tx.B.Source); !found {
			// 	return
			// }
		}
```

I figure, remaining target information is using more resources so we should be careful :)

File: lib/block_transaction.go [hunk 2]
```diff
@@ -114,6 +115,10 @@ func (bt *BlockTransaction) Save(st *sebakstorage.LevelDBBackend) (err error) {
 	} else if exists {
 		return sebakerror.ErrorBlockAlreadyExists
 	}
+	for _, op := range bt.transaction.B.Operations {
+		target := op.B.TargetAddress()
+		bt.Targets = append(bt.Targets, target)
+	}
```
Comment (Geod24) [inline lib/block_transaction.go]: Why do we duplicate this data ?

File: lib/node_runner_checker.go (hunk 1 above)
Comment (Geod24) [reply lib/node_runner_checker.go]: I second this. I thought we were not supposed to check the target address ?
