### PR TITLE
fixed bugs from latest new-proposer

### LINKED ISSUE #216: The new ISAAC voting process(SIGN, ACCEPT)
### Voting Process
Originally the new model will have 2 voting process,

* `SIGN`: voting for received Ballot from proposer
* `ACCEPT`: voting for confirmed Ballot of each validator

In `ACCEPT` state, validator will compare the voting result of the other validators with his/her voting result.

In #215, `SIGN` and `ACCEPT` voting process is not yet implemented. Therefore, it will be completed in with this issue :)

### PR DESCRIPTION
**Pull request by spikeekips**
### Github Issue
resolve #216 

### Background
The latest commit, ab675b4428e57fafb10fd2645bc3654d8d654255 of new-proposer has some bugs.

* `cmd/sebak/cmd/run.go` does not have `SIGN` and `ACCEPT` threshold.
* `CheckNodeRunnerHandleACCEPTBallotValidateResult` is duplicated with `CheckNodeRunnerHandleBallotCheckResult`.
* `checker.FinishedVotingHole` in `checker.NodeRunner.Consensus().CloseConsensus()` 
* `checkTransactionSourceCheck` moved to `Transaction.Validate()`
* some test code fixed.

I tried to fix them. And further more, added documentations for functions in `node_runner_checker.go` and `node_runner_transaction_checker.go`.

### CODE REVIEW

**Comment by Geod24** [comment]
"Fix bug" is not very descriptive...

**Comment by spikeekips** [comment]
@Geod24 I listed some bugs in description. Thanks.

File: lib/transaction.go [hunk 1]
```diff
@@ -108,11 +108,51 @@ func (tx Transaction) IsWellFormed(networkID []byte) (err error) {
 	return
 }
 
+// Validate checks,
+// * source account exists
+// * checkpoint is valid
+// * source has enough balance to pay
+// * and it's `Operations`
```
Comment (Charleslee522) [inline lib/transaction.go]: 👍

File: cmd/sebak/cmd/run.go [hunk 2]
```diff
@@ -44,19 +44,21 @@ var (
 	flagTLSCertFile         string = sebakcommon.GetENVValue("SEBAK_TLS_CERT", "sebak.crt")
 	flagTLSKeyFile          string = sebakcommon.GetENVValue("SEBAK_TLS_KEY", "sebak.key")
 	flagValidators          string = sebakcommon.GetENVValue("SEBAK_VALIDATORS", "")
-	flagThreshold           string = sebakcommon.GetENVValue("SEBAK_THRESHOLD", "66")
+	flagSIGNThreshold       string = sebakcommon.GetENVValue("SEBAK_SIGN_THRESHOLD", "66")
+	flagACCEPTThreshold     string = sebakcommon.GetENVValue("SEBAK_ACCEPT_THRESHOLD", "66")
```
Comment (Geod24) [inline cmd/sebak/cmd/run.go]: Isn't that a revert to the state in master ? Why do we have 2 different thresholds ?

File: lib/storage/dbbackend.go [hunk 3]
```diff
@@ -1,17 +0,0 @@
...
-	Remove(string) error
-
-	GetIterator(prefix string, reverse bool) (func() (IterItem, bool), func())
-
-	News(...Item) error
-	Sets(...Item) error
-
-	Commit() error
-	Discard() error
-}
```
Comment (Geod24) [inline lib/storage/dbbackend.go]: Why do you remove those ? Looks unrelated

File: lib/transaction.go [hunk 4]
```diff
@@ -108,11 +108,51 @@ func (tx Transaction) IsWellFormed(networkID []byte) (err error) {
...
+	totalAmount := tx.TotalAmount(true)
+
+	// check, have enough balance at checkpoint
+	if sebakcommon.MustAmountFromString(bac.Balance) < totalAmount {
+		err = sebakerror.ErrorTransactionExcessAbilityToPay
+		return
+	}
+
+	// check, have enough balance now
+	if sebakcommon.MustAmountFromString(ba.Balance) < totalAmount {
```
Comment (Geod24) [inline lib/transaction.go]: This is the same as the previous check, it does not check for left balance

File: lib/transaction.go [hunk 5]
```diff
@@ -108,11 +108,51 @@ func (tx Transaction) IsWellFormed(networkID []byte) (err error) {
...
+		err = sebakerror.ErrorTransactionExcessAbilityToPay
+		return
+	}
+
+	for _, op := range tx.B.Operations {
```
Comment (Geod24) [inline lib/transaction.go]: I would say move this before the balance check, because if any operation is invalid `TotalAmount` does not make sense / could error out.

File: cmd/sebak/cmd/run.go [hunk 6]
```diff
@@ -44,19 +44,21 @@ var (
...
-	storageConfig *sebakstorage.Config
-	validators    []*sebaknode.Validator
-	threshold     int
-	logLevel      logging.Lvl
-	log           logging.Logger
+	kp              *keypair.Full
+	nodeEndpoint    *sebakcommon.Endpoint
+	storageConfig   *sebakstorage.Config
+	validators      []*sebaknode.Validator
+	signThreshold   int
```
Comment (cmcm2222) [inline cmd/sebak/cmd/run.go]: Do we need 2 threshold paramater??

File: cmd/sebak/cmd/run.go [hunk 7]
```diff
@@ -194,8 +197,11 @@ func parseFlagsNode() {
 		common.PrintFlagsError(nodeCmd, "--storage", err)
 	}
 
-	if threshold, err = strconv.Atoi(flagThreshold); err != nil {
-		common.PrintFlagsError(nodeCmd, "--threshold", err)
+	if signThreshold, err = strconv.Atoi(flagSIGNThreshold); err != nil {
```
Comment (cmcm2222) [inline cmd/sebak/cmd/run.go]: Same as previous question.

Comment (spikeekips) [reply cmd/sebak/cmd/run.go]: @cmcm2222 As I understand our new proposer model, the voting will be done in 2 state transition, `INIT` -> `SIGN` and `SIGN` -> `ACCEPT`.

File: lib/storage/dbbackend.go (hunk 3 above)
Comment (spikeekips) [reply lib/storage/dbbackend.go]: @Geod24 Oops, it's mistake 👍

File: cmd/sebak/cmd/run.go (hunk 2 above)
Comment (spikeekips) [reply cmd/sebak/cmd/run.go]: https://github.com/bosnet/sebak/pull/240#discussion_r209826426

File: lib/transaction.go (hunk 5 above)
Comment (spikeekips) [reply lib/transaction.go]: @Geod24 We can choose the proper position of this block. Anyway `Operation.Validate` is more expensive than checking `TotalAmount`.

File: cmd/sebak/cmd/run.go (hunk 7 above)
Comment (Geod24) [reply cmd/sebak/cmd/run.go]: But why would you want a different threshold ? That sounds quite dangerous.

**Comment by spikeekips** [comment]
> @Geod24 : The integration tests tells me this is not ready.

Yes. I can fix it.

File: cmd/sebak/cmd/run.go (hunk 7 above)
Comment (spikeekips) [reply cmd/sebak/cmd/run.go]: @Geod24 Hmm, it would be better node operator to set the threshold, but if it can be matter, how about limit the minimum threshold like 66%.

Comment (spikeekips) [reply cmd/sebak/cmd/run.go]: @Geod24 So do you think the threshold option will be useless?

Comment (Geod24) [reply cmd/sebak/cmd/run.go]: At the moment, I don't see any reason for it to be configurable. In other words, [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).

Comment (spikeekips) [reply cmd/sebak/cmd/run.go]: @Geod24 If you mean only for SEBAK, the current threshold option is not important, it can be set in inside variable. :)

**Comment by spikeekips** [comment]
The integration test failed because it was too short until consensus. For more details, see 36be761 . This commit maybe need the more additional patches :)

**Comment by Geod24** [comment]
Okay, but the test was waiting 5 seconds. How long does it take to reach consensus now ?

**Comment by spikeekips** [comment]
> @Geod24 : Okay, but the test was waiting 5 seconds. How long does it take to reach consensus now ?

At this time, we can not convince how long does it takes, but in normal env I guess 5 ~10 seconds. The env of integration test does not reflect the real env, so `getAccountWithBalance()` will wait almost 10 seconds.

File: cmd/sebak/cmd/run.go (hunk 7 above)
Comment (Geod24) [reply cmd/sebak/cmd/run.go]: My point is that we should just hardcode it to 67% for the time being and revise that when this kind of tweaks is needed (when we open the network).

Comment (spikeekips) [reply cmd/sebak/cmd/run.go]: @Geod24 Yes, I agree. It can be hardcoded. If I have a right to decision, I will leave the threshold related options, it will be useful to control or test.

**Comment by spikeekips** [comment]
@Geod24 threshold part is ancient code, so we can decide to keep or remove at anytime later. Please review the rest of part.

**Comment by spikeekips** [comment]
@Geod24 Yes, same threshold will be reasonable, I agree. We can choose later. At this time we will set the 2 threshold value for SIGN and ACCEPT in cmd options.

**Comment by spikeekips** [comment]
@Geod24 Ping a316fbbfae7393bef7c462de0a3c9d6b94ac6297

File: lib/node_runner.go [hunk 8]
```diff
@@ -367,27 +290,21 @@ func (nr *NodeRunner) handleBallotMessage(message sebaknetwork.Message) (err err
...
 		VotingHole:     VotingNOTYET,
 	}
-	err = sebakcommon.RunChecker(baseChecker, nr.handleBaseBallotCheckerDeferFunc)
+	err = sebakcommon.RunChecker(baseChecker, nr.handleMessageCheckerDeferFunc)
 	if err != nil {
 		if _, ok := err.(sebakcommon.CheckerErrorStop); !ok {
-			nr.log.Debug("failed to handle ballot", "error", err, "state", "base")
 			return
 		}
-		nr.log.Debug("stop handling ballot", "reason", err, "state", "base")
```
Comment (Geod24) [inline lib/node_runner.go]: Why are those removed ? And why were they `Debug` to begin with ?

File: lib/node_runner.go [hunk 9]
```diff
@@ -325,16 +250,15 @@ func (nr *NodeRunner) handleMessage() {
 
 		if err != nil {
 			if _, ok := err.(sebakcommon.CheckerErrorStop); ok {
-				nr.log.Debug("consensus finished", "message", message.Head(50), "error", err)
 				continue
 			}
-			nr.log.Debug("failed to handle sebaknetwork.Message", "message", message.Head(50), "error", err)
+			nr.log.Debug("stop handling sebaknetwork.Message", "message", message.Head(50), "error", err)
```
[the remark this answers is not in the document]
Comment (spikeekips) [reply lib/node_runner.go]: @Geod24 Yes, you right. "stop" is not proper in this context.

File: lib/node_runner.go [hunk 10]
```diff
@@ -325,16 +250,15 @@ func (nr *NodeRunner) handleMessage() {
...
 		}
 	}
 }
 
 func (nr *NodeRunner) handleMessageFromClient(message sebaknetwork.Message) (err error) {
-	nr.log.Debug("got message from client`", "message", message.Head(50))
+	nr.log.Debug("got message`", "message", message.Head(50))
```
[the remark this answers is not in the document]
Comment (spikeekips) [reply lib/node_runner.go]: @Geod24 I agree, we can also remove 'from client' things from `sebaknetwork.MessageType`. I think we can handle this issue in another issue.

File: lib/node_runner.go [hunk 11]
```diff
@@ -441,7 +356,7 @@ func (nr *NodeRunner) InitRound() {
 		}
 	}
 
-	nr.log.Debug("all validators are checked for connectivity")
+	nr.log.Debug("connectivity checked")
```
[the remark this answers is not in the document]
Comment (spikeekips) [reply lib/node_runner.go]: @Geod24 Good. I will change it.

File: lib/node_runner.go (hunk 8 above)
Comment (spikeekips) [reply lib/node_runner.go]: @Geod24 Oops, it's mistakes including `Debug`. I'll recover them.

File: lib/node_runner.go [hunk 12]
```diff
@@ -167,146 +202,36 @@ func (nr *NodeRunner) ConnectValidators() {
...
+	nr.handleMessageCheckerDeferFunc = f
 }
 
 func (nr *NodeRunner) handleMessage() {
 	for message := range nr.network.ReceiveMessage() {
 		var err error
 
 		if message.IsEmpty() {
-			nr.log.Error("got empty message`")
+			nr.log.Debug("got empty message`")
```
Comment (Geod24) [inline lib/node_runner.go]: Could you explain why this was changed ?

Comment (spikeekips) [reply lib/node_runner.go]: @Geod24 Oops, it should be `Error`.

File: lib/node_runner.go [hunk 13]
```diff
@@ -344,11 +268,10 @@ func (nr *NodeRunner) handleMessageFromClient(message sebaknetwork.Message) (err
...
 	}
 
-	if err = sebakcommon.RunChecker(checker, nr.handleMessageFromClientCheckerDeferFunc); err != nil {
-		if _, ok := err.(sebakcommon.CheckerErrorStop); ok {
-			return
+	if err = sebakcommon.RunChecker(checker, nr.handleMessageCheckerDeferFunc); err != nil {
+		if _, ok := err.(sebakcommon.CheckerErrorStop); !ok {
+			nr.log.Error("failed to handle message from client", "error", err)
 		}
-		nr.log.Error("failed to handle message from client", "error", err)
```
Comment (Geod24) [inline lib/node_runner.go]: So if it's another kind of error than `CheckerErrorStop` we are not logging it ?

Comment (spikeekips) [reply lib/node_runner.go]: @Geod24 This will `log.Error` except `sebakcommon.CheckerErrorStop`.

Comment (Geod24) [reply lib/node_runner.go]: Oh right I misread

**Comment by spikeekips** [comment]
@Geod24 Thanks.
