### PR TITLE
Fixed the empty `Ballot.H.Hash`

### LINKED ISSUE #451: `Ballot.H.Hash` is empty
```
{
  "H": {
    "hash": "",
    "signature": "4fB1WARoTKgWMB4XuDoR3nUQnmbDm3DnobXRcFP2wWBRTGjn4AuqrqgohHCh6k5jW46B8VveMHFxiHC37PHNXGwn",
    "proposer-signature": "5SYmGsRoGeHkPtgdM3F3ezph6WpU8kUNFAoNU5fJQiwQuTeGfqyyFUBtQkgvp2PCLFgtoynTYUYSD5zb9o7ZpedD"
  },
  "B": {
    "confirmed": "2018-09-27T08:07:18.759237196+09:00",
    "proposed": {
      "confirmed": "2018-09-27T08:07:18.670256012+09:00",
      "proposer": "GDFMZZFEYW2JDX4MDGH6DRPA446BMLCK2NIEYFJFDTNA426VDI3YNQOZ",
      "round": {
        "number": 0,
        "block-height": 1,
        "block-hash": "hahaha",
        "total-txs": 1
      },
      "transactions": [
        "B7RQ2u1Uw7e3D9Fdz5Rr2xQMQBhZTDAeBvvQk2PLKAGN"
      ]
    },
    "source": "GDFMZZFEYW2JDX4MDGH6DRPA446BMLCK2NIEYFJFDTNA426VDI3YNQOZ",
    "state": 1,
    "vote": "NOT-YET",
    "reason": null
  }
}
```

### PR DESCRIPTION
**Pull request by spikeekips**
### Github Issue

resolves #451 

### Background

The `Ballot.H.Hash` is empty in the serialized output.

### Solution

This was caused by `rlp.Encode()` for `errors.Error.Data`.

### CODE REVIEW

File: lib/error/base.go [hunk 1]
```diff
@@ -18,26 +24,52 @@ func (o *Error) Error() string {
...
 		for k, v := range o.Data {
-			data[k] = v
+			new.Data[k] = v
+		}
+	}
+
+	return &new
+}
+
+func (o *Error) EncodeRLP(w io.Writer) (err error) {
```
Comment (kfangw) [inline lib/error/base.go]: Sorry that I missed this one in the previous review.
